services:

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - backend_cache:/app/cache
    environment:
      - APP_ENVIRONMENT=production
      - QDRANT_HOST=qdrant
      - OLLAMA_BASE_URL=http://ollama:11434
    env_file:
      - path: ./openai.env
        required: false
    depends_on:
      - qdrant
      - ollama
  
  qdrant:
    image: qdrant/qdrant
    restart: always
    volumes:
      - qdrant:/qdrant/storage
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml

  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama:/root/.ollama
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  backend_cache:
  ollama:
  qdrant:

configs:
  qdrant_config:
    content: |
      telemetry_disabled: true
