name: Backend tests

on: 
  push:
    branches:
      - main
      - dev-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements_tests.txt
      - name: Install pytest
        run: pip install pytest
      - name: Test with pytest
        run: pytest backend
